<?php
/**
 * Created by PhpStorm.
 * User: naffan
 * Date: 2019/2/21
 * Time: 4:16 PM
 */
namespace App\Facades\GeoIp\Facade;

use Illuminate\Support\Facades\Facade;

class GeoIP extends Facade{
    protected static function getFacadeAccessor()
    {
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        return 'geoip';
    }
}